apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasky-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tasky
  template:
    metadata:
      labels:
        app: tasky
    spec:
      containers:
      - name: tasky
        image: 724772080029.dkr.ecr.us-east-1.amazonaws.com/tasky-app:11
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_URI
          value: "mongodb://172.31.37.2:27017/taskydb"

